[workspace]

[package]
name = "xtask"
version = "1.5.0"
authors = ["Apollo Graph, Inc. <packages@apollographql.com>"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
camino = "1"
clap = { version = "4.5.1", features = ["derive"] }
cargo_metadata = "0.19.0"
# Only use the `clock` features of `chrono` to avoid the `time` dependency
# impacted by CVE-2020-26235.  https://github.com/chronotope/chrono/issues/602
# and https://github.com/chronotope/chrono/issues/1073 will explain more.
chrono = { version = "0.4.34", default-features = false, features = ["clock"] }
console = "0.15.8"
dialoguer = "0.11.0"
graphql_client = "0.14.0"
itertools = "0.14.0"
libc = "0.2"
memorable-wordlist = "0.1.7"
nu-ansi-term = "0.50"
once_cell = "1"
regex = "1.10.3"
reqwest = { version = "0.11", default-features = false, features = [
  "blocking",
  "json",
  "rustls-tls",
  "rustls-tls-native-roots",
] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1"
tempfile = "3"
tinytemplate = "1.2.1"
tokio = { version = "1.36.0", features = ["full"] }
which = "7.0.0"

[dev-dependencies]
insta = { version = "1.43.1", features = ["json", "redactions", "yaml"] }
